name: last_flutter_flex_player
description: "A Flutter package to play video from youtube, and direct video
  links with custom UI."
version: 0.0.1
homepage: "https://github.com/ayahsujana/"
repository: "https://github.com/ayahsujana/last_flutter_flex_player"

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audio_video_progress_bar: ^2.0.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  html: ^0.15.4
  http: ^1.2.2
  plugin_platform_interface: ^2.1.8
  rxdart: null
  wakelock_plus: ^1.2.8
  youtube_explode_dart: ^2.3.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_flex_player
        pluginClass: FlutterFlexPlayerPlugin
      ios:
        pluginClass: FlutterFlexPlayerPlugin
      macos:
        pluginClass: FlutterFlexPlayerPlugin

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
